### ISSUE TITLE
iframes with style position:absolute are not working 

### ISSUE THREAD

**Issue by nilssrvd** [hydescarf/Obsidian-Theme-Mado-11#13] opened 2022-10-15 10:57 UTC
I took it upon myself to check that those iframes are working in all the other Obsidian Themes and so it is; it's possible to embed iframes in the entirety of a note. Not on Mado 11. The note just appears empty in reading mode. I have no idea what could be causing this, but it's unique to this Theme as far as I know.

Here is a simple line of HTML code to test the functionality:

`<iframe src="https://es.wikipedia.org/wiki/Biblia" style="position:absolute; top:0; left:0; width:100%; border:none; height:100%;"></iframe>`

That said, let me tell you that your work with this Theme is fabulous, the best I've seen in styling for Obsidian.

**Comment by hydescarf** [comment] 2022-10-15 13:36
I assume you are currently on <v0.16, as Mado-11 is disabled for v1.0.  
My app has auto-updated to the latest version now, so I might as well just rewrite the code for v1.0 and look out for the iframe issue. Thanks for the report!

**Comment by nilssrvd** [comment] 2022-10-20 12:29
> I assume you are currently on <v0.16, as Mado-11 is disabled for v1.0.  
> My app has auto-updated to the latest version now, so I might as well just rewrite the code for v1.0 and look out for the iframe issue. Thanks for the report!

I am also on _v1.0_. Since Mado isn't listed there as a Legacy Theme, I assumed it was already updated to work with _v1.0_. I imagine that this may be in fact a problem associated with the aforementioned update. Hoping my report will help you!

**Comment by hydescarf** [comment] 2022-11-01 04:02
The theme is now updated to v1.0.
Although I didn't find any issue occurring on v1.0 (with both old and new version of the theme), let me know if it persists.
If anything, I do notice the lag of loading which causes the reading mode to be empty, for a few seconds.

**Comment by nilssrvd** [comment] 2022-11-01 11:26
> The theme is now updated to v1.0.
> Although I didn't find any issue occurring on v1.0 (with both old and new version of the theme), let me know if it persists.
> If anything, I do notice the lag of loading which causes the reading mode to be empty, for a few seconds.

This is great, thank you. The problem I mentioned before seems to be completely resolved now.

There is anyway a problem with this bottom bar in the next picture. Do you know what could be causing it? Or is it not a problem since Mado 11 is just not coded to show it?

![Problem bottom bar.png](https://user-images.githubusercontent.com/61798811/199222723-27c5708b-bdf3-4a9e-a311-89bd60911b63.png)

Of courses, when I hover over the bar,s location with the mouse it doesn't appear, which could not be seen in the image.

**Comment by hydescarf** [comment] 2022-11-01 23:25
Glad to hear the issue is resolved!
Oh yeah, status bar is now hidden by default (and not hover-able), it can be toggled to be shown all time through Style Settings.

**Comment by hydescarf** [comment] 2022-11-04 13:41
I'll close this issue now as the main problem is resolved!

**Closed by hydescarf** 2022-11-04 13:41 UTC
